--Product Analysis using SQL

-- 1. What is the total revenue generated by each product category?
SELECT product_category, 
	ROUND(SUM(total), 2) AS Revenue
FROM ordersproject
JOIN products
ON ordersproject.product_id = products.product_id
GROUP BY product_category;

-- 2.How many unique products have been ordered?
SELECT DISTINCT(COUNT(product_name)) AS Unique_Products
FROM products;

-- 3. What is the total revenue generated each year?
SELECT 
    YEAR(order_date) AS Year_revenue,
    FORMAT(SUM(total), 'N2') AS Revenue
FROM 
    ordersproject
GROUP BY 
    YEAR(order_date);

-- 4. What is the date of the latest and earliest order?
SELECT MIN(order_date) 'Earliest Date',
	MAX(order_date) Latest_date
FROM ordersproject;

-- 6. What product category has the lowest average price of products?
SELECT Top 1 product_category,
	ROUND(AVG(retail_price), 2) Average_price
FROM ordersproject
JOIN products on ordersproject.product_id=products.product_id
GROUP BY product_category
ORDER BY Average_price;

-- 7. What are the top 10 highest performing products?
SELECT Top 10 product_name,
	ROUND(SUM(total), 2) Revenue
FROM ordersproject 
JOIN products
on ordersproject.product_id=products.product_id
GROUP BY product_name
ORDER BY Revenue DESC;

-- 8. Show the total revenue and profit generated by each account_manager?
SELECT account_manager,
	ROUND(SUM(total), 2) Revenue,
        ROUND(SUM(total) - SUM(cost_price), 2) Profit
FROM ordersproject
JOIN account_managers
on ordersproject.account_id=account_managers.account_id
GROUP BY account_manager
ORDER BY Revenue DESC;

--  9. What is the name, city and account manager of the highest selling product in 2017?
SELECT TOP 1 product_name,
	city,
        account_manager,
        ROUND(SUM(total),2) as Revenue
FROM ordersproject
JOIN products
on ordersproject.product_id=products.product_id
JOIN account_managers
on ordersproject.account_id=account_managers.account_id
WHERE Year(order_date) = 2017
GROUP BY product_name, city, account_manager
ORDER BY Revenue DESC;

-- 10. Find the mean amount spent per order by each Customer type?
SELECT customer_type,
	ROUND(AVG(total),2) as Average_amount
FROM ordersproject
GROUP BY customer_type;

--11. What is the 5th highest selling product? 
/*SELECT Top 1 product_name,
	city,
        account_manager,
        ROUND(SUM(total),2) as Revenue
FROM ordersproject
JOIN products
on ordersproject.product_id=products.product_id*/

SELECT TOP 1 product_name, Revenue
FROM (
    SELECT TOP 5 product_name, ROUND(SUM(total),2) as Revenue, products.product_id
    FROM ordersproject
	JOIN products  on ordersproject.product_id=products.product_id
    GROUP BY product_name, products.product_id
    ORDER BY Revenue DESC
) AS Top5Products
Order by Revenue ASC;